### ISSUE TITLE
1주차 개념스터디: RestAPI

### ISSUE THREAD

**Issue by keltion** [dev-immersion/2021-summer#5]
RestAPI는 rest기반의 규칙들을 지켜 설계된 API. 즉, 각 자원마다 고유한 URL을 부여하고 이 자원들을 HTTP method를 이용하여 CRUD할 수 있는 API라는 것은 이해를 하였습니다.

## question 1
그런데 REST에 대한 깊은 이해를 하고싶었고 위키피디아를 참고하여 REST를 공부하고 나름대로 이해를 해보았지만 제가 이해한 것이 맞는지 의문이 듭니다. 다음은 위키피디아에서 REST를 설명하는 글의 일부입니다.

> REST is a software architectural style that was created to guide the design and development of the architecture for the World Wide Web. 

> The goal of REST is to increase performance, scalability, simplicity, modifiability, visibility, portability, and reliability. This is achieved through following REST principles such as a client–server architecture, statelessness, cacheability, use of a layered system, support for code on demand, and using a uniform interface. These principles must be followed for the system to be classified as REST.

위 내용을 참고하여 REST에 대해 다음과 같이 정리해보았습니다.

REST는 웹서비스 구성시 서비스의 performance, scalability, simplicity 등의 목표를 달성하기 위해 만들어진 설계도이며 이 목표를 위해서 원칙들을 만들었습니다. 그 원칙에는 uniform interface, stateless, cacheable 등이 있으며 흔히 REST를 설명할 때 말하는 "해당 자원의 상태를 주고받는 모든 것"은 원칙 중 uniform interface를 의미합니다.

끝으로 REST API는 위의 원칙들을 지켜 웹서비스를 제공하여 client가 API이용시 좋은 performance와 simplicity(간단한 사용), scalablility(높은 확장성)이라는 장점을 얻을 수 있도록 설계한 API입니다.  

혹시 잘못 이해한 부분이 있다면 알려주실 수 있나요?

## question 2
몇 몇 사이트에서는 REST를 다음과 같이 정의하기도 합니다.
> It is architectural style for distributed hypermedia systems

Web은 hyperlink를 이용하여 다양한 자료들을 연결해줍니다. 이런 많은 데이터들을 관리하고 제공하기 위해서는 여러대의 서버를 이용해야하는데, 이럴 때 stateful한 방식을 사용하면 인증된 서버에 클라이언트가 요구하는 데이터가 존재하지않아 다른 서버에 클라이언트가 접근하고자하면 session을 복사해야하는 추가적인 연산이 발생하므로 REST는 stateless 방식을 사용하여 이런 문제들을 해결하는 architectural style이다.

이런식으로 이해했는데 저 문장의 의미를 잘 이해한건지 모르겠고 너무 state에 치우쳐서 이해한 것 같습니다. 위 문장의 이해가 잘못된다면 지적해주실 수 있나요?

**Comment by appleg1226** [comment]
## Q1
작성하시고 정리하신 내용에 크게 문제점은 없는 것 같습니다.

## Q2
state 관련해서 저도 깊게 생각해본 적은 없었는데, 찾아보던 중 괜찮은 자료가 있어서 공유해 드립니다.
https://5equal0.tistory.com/entry/StatefulStateless-Stateful-vs-Stateless-%EC%84%9C%EB%B9%84%EC%8A%A4%EC%99%80-HTTP-%EB%B0%8F-REST

state를 중심으로 이해를 해보시려고 한 시도 자체는 전 긍정적입니다.
사실 저도 이만큼 고민해본 적이 없어서..
딱히 문제가 되는 내용은 없는 것 같습니다.

## 추가적으로
제 경험상 REST API에 대해서는 관련 개념 이해도 중요하지만,
실제로 어떤 방식으로 구축하는지를 함께 배우는 것이 중요하다고 생각합니다.

이번에는 가볍게 정리하시고 이후에 실제로 REST API를 경험한 뒤에,
다시 한 번 확인해본다면 그땐 조금 더 제대로 이해 될 겁니다.

추가 질문 있으시면 계속 남겨주세요...

**Comment by keltion** [comment]
답변과 조언 감사드립니다. 공유해 주신 자료를 공부하면서 RestAPI는 stateless방식을 이용하여 서버와 통신을 하기때문에 서버에 session을 저장하지 않는 것을 다시 확인하였습니다. 그런데 인증이 필요한 상황에서는 서버에 session을 저장하지 않고 어떻게 클라이언트에게 권한을 부여하는지 궁금했고 찾아본 결과 토큰방식을 이용하여 클라이언트에게 토큰을 제공하고 클라이언트가 서버에 데이터를 요청할 때 토큰을 같이 전달해줌으로써 서버는 이를 검증하는 식으로 권환에 따른 데이터를 반환하는 것을 알게 되었습니다.

그러자 결국 토큰 또한 올바른 토큰인지 아닌지를 판단하기 위해서 서버에 해당 토큰을 저장해야 하니 결국 session과 마찬가지로 브라우저 측 정보를 저장하고 있는 셈이 아닐까? 생각하게 되었고 어떠한 식으로 서버에서 토큰을 관리하는지에 대해서 더 공부해보았습니다. 

토큰은 header+payload+ virify signature로 구성되어 있으며 서버에게 발급받은 토큰을 브라우저가 다시 서버로 보낼 때 header와 payload를 각각 base64인코딩한 후 서버에서 발급하는 secret키와 함께 합쳐 header에 명시된 해시 알고리즘으로 인코딩한 후에 원래 토큰의 해시값과 비교하여 verification을 진행합니다. 

결과적으로 브라우저의 토큰을 서버에 저장하여 관리하는 것이 아니라 브라우저에 부여한 토큰을 해시함수를 통해서 검증함으로써 서버 측에는 토큰검증을 위한 브라우저 측 정보를 따로 저장할 필요가 없게 됩니다.

위와 같은 결론을 냈는데 이렇게 알고있어도 괜찮을까요?

**Comment by keltion** [comment]
> ## Q1
> 작성하시고 정리하신 내용에 크게 문제점은 없는 것 같습니다.
> 
> ## Q2
> state 관련해서 저도 깊게 생각해본 적은 없었는데, 찾아보던 중 괜찮은 자료가 있어서 공유해 드립니다.
> https://5equal0.tistory.com/entry/StatefulStateless-Stateful-vs-Stateless-%EC%84%9C%EB%B9%84%EC%8A%A4%EC%99%80-HTTP-%EB%B0%8F-REST
> 
> state를 중심으로 이해를 해보시려고 한 시도 자체는 전 긍정적입니다.
> 사실 저도 이만큼 고민해본 적이 없어서..
> 딱히 문제가 되는 내용은 없는 것 같습니다.
> 
> state가 있다면 클라이언트와 서버간에 서로 기억해야할 것이 있기 때문에 보통 서버에서는 session을 사용하지요.
> 이렇게 했을 때 session의 관리 비용이 증가하고, 추후에 서버가 증가할 경우에는 그 비용이 더 복잡해집니다.
> 애초에 서로간에 상태 유지를 하지 않는다면, 그런 비용 자체도 줄어들뿐 아니라, 더 간단한 사용이 가능해집니다.
> 그런 데에서 rest api의 강점이 있는 것 같습니다
> 
> ## 추가적으로
> 제 경험상 REST API에 대해서는 관련 개념 이해도 중요하지만,
> 실제로 어떤 방식으로 구축하는지를 함께 배우는 것이 중요하다고 생각합니다.
> 
> 이번에는 가볍게 정리하시고 이후에 실제로 REST API를 경험한 뒤에,
> 다시 한 번 확인해본다면 그땐 조금 더 제대로 이해 될 겁니다.
> 
> 추가 질문 있으시면 계속 남겨주세요...

**Comment by appleg1226** [comment]
JWT(Json Web Token) 인증 방식을 추가적으로 공부하신 것 같네요!
안 그래도 나중에 이것도 추가적으로 스터디할 수 있도록 준비하려고 했는데, 미리 하셨군요.

보통 위의 내용은 하나의 주제로 다뤄지는 큰 내용이기 때문에,
REST API에 대해서라면 이 정도면 충분한 것 같습니다.

**Comment by keltion** [comment]
답변 감사드립니다!
